name: Get Project Version

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build
        run: npm install && npm run build

      - name: Get project version
        id: get-version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"